-- Database-backed generated chat names with event-scoped sequential suffixes.
-- Run after supabase/chat-generated-identity-remove-avatars.sql.

create table if not exists public.chat_name_pool (
  id bigint generated by default as identity primary key,
  base_name text not null,
  normalized_name text not null,
  region_group text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint chat_name_pool_base_name_not_empty check (btrim(base_name) <> ''),
  constraint chat_name_pool_normalized_name_not_empty check (btrim(normalized_name) <> ''),
  constraint chat_name_pool_region_group_check check (region_group in ('western', 'international'))
);

create unique index if not exists chat_name_pool_normalized_name_idx
on public.chat_name_pool(normalized_name);

alter table public.chat_name_pool enable row level security;
revoke select, insert, update, delete on public.chat_name_pool from anon, authenticated;

create table if not exists public.chat_name_pool_exclusions (
  normalized_name text primary key,
  source_name text not null,
  reason_category text not null,
  created_at timestamptz not null default now()
);

alter table public.chat_name_pool_exclusions enable row level security;
revoke select, insert, update, delete on public.chat_name_pool_exclusions from anon, authenticated;

insert into public.chat_name_pool_exclusions (normalized_name, source_name, reason_category)
values
  ('admin', 'admin', 'reserved system name'),
  ('administrator', 'administrator', 'reserved system name'),
  ('artist', 'artist', 'reserved system name'),
  ('moderator', 'moderator', 'reserved system name'),
  ('mod', 'mod', 'reserved system name'),
  ('official', 'official', 'reserved system name'),
  ('system', 'system', 'reserved system name'),
  ('support', 'support', 'reserved system name'),
  ('hitler', 'hitler', 'extremist/historical abuse'),
  ('stalin', 'stalin', 'extremist/historical abuse'),
  ('mussolini', 'mussolini', 'extremist/historical abuse'),
  ('putin', 'putin', 'political'),
  ('trump', 'trump', 'political'),
  ('biden', 'biden', 'political'),
  ('obama', 'obama', 'political'),
  ('bolsonaro', 'bolsonaro', 'political'),
  ('xi', 'xi', 'political'),
  ('lenin', 'lenin', 'extremist/historical abuse'),
  ('thatcher', 'thatcher', 'political'),
  ('reagan', 'reagan', 'political'),
  ('gandhi', 'gandhi', 'political'),
  ('bush', 'bush', 'political'),
  ('castro', 'castro', 'political'),
  ('chavez', 'chavez', 'political'),
  ('cheney', 'cheney', 'political'),
  ('churchill', 'churchill', 'political'),
  ('clinton', 'clinton', 'political'),
  ('gorbachev', 'gorbachev', 'political'),
  ('macron', 'macron', 'political'),
  ('mandela', 'mandela', 'political'),
  ('merkel', 'merkel', 'political'),
  ('modi', 'modi', 'political'),
  ('napoleon', 'napoleon', 'political'),
  ('nixon', 'nixon', 'political'),
  ('roosevelt', 'roosevelt', 'political'),
  ('trudeau', 'trudeau', 'political'),
  ('truman', 'truman', 'political'),
  ('beyoncé', 'beyoncé', 'impersonation'),
  ('bezos', 'bezos', 'impersonation'),
  ('biggie', 'biggie', 'impersonation'),
  ('elon', 'elon', 'impersonation'),
  ('eminem', 'eminem', 'impersonation'),
  ('kanye', 'kanye', 'impersonation'),
  ('kobe', 'kobe', 'impersonation'),
  ('lebron', 'lebron', 'impersonation'),
  ('madonna', 'madonna', 'impersonation'),
  ('messi', 'messi', 'impersonation'),
  ('oprah', 'oprah', 'impersonation'),
  ('pele', 'pele', 'impersonation'),
  ('ronaldo', 'ronaldo', 'impersonation'),
  ('snoop', 'snoop', 'impersonation'),
  ('tupac', 'tupac', 'impersonation'),
  ('zuckerberg', 'zuckerberg', 'impersonation'),
  ('gay', 'gay', 'safety'),
  ('gypsy', 'gypsy', 'safety'),
  ('whitey', 'whitey', 'safety'),
  ('dick', 'dick', 'profanity'),
  ('four', 'four', 'malformed'),
  ('fifty', 'fifty', 'malformed'),
  ('eleven', 'eleven', 'malformed'),
  ('xx', 'xx', 'malformed'),
  ('zero', 'zero', 'malformed'),
  ('code', 'code', 'malformed'),
  ('project', 'project', 'malformed'),
  ('skills', 'skills', 'malformed')
on conflict (normalized_name) do update
set source_name = excluded.source_name,
    reason_category = excluded.reason_category;

insert into public.chat_name_pool (base_name, normalized_name, region_group, is_active)
values
  ('Aaliyah', public.normalize_chat_name('Aaliyah'), 'western', true),
  ('Aaron', public.normalize_chat_name('Aaron'), 'western', true),
  ('Abby', public.normalize_chat_name('Abby'), 'western', true),
  ('Abel', public.normalize_chat_name('Abel'), 'western', true),
  ('Adam', public.normalize_chat_name('Adam'), 'western', true),
  ('Adele', public.normalize_chat_name('Adele'), 'western', true),
  ('Adrianne', public.normalize_chat_name('Adrianne'), 'western', true),
  ('Adriana', public.normalize_chat_name('Adriana'), 'western', true),
  ('Aiko', public.normalize_chat_name('Aiko'), 'international', true),
  ('Aisha', public.normalize_chat_name('Aisha'), 'international', true),
  ('Aj', public.normalize_chat_name('Aj'), 'western', true),
  ('Alan', public.normalize_chat_name('Alan'), 'western', true),
  ('Alanis', public.normalize_chat_name('Alanis'), 'western', true),
  ('Albert', public.normalize_chat_name('Albert'), 'western', true),
  ('Alex', public.normalize_chat_name('Alex'), 'western', true),
  ('Alexander', public.normalize_chat_name('Alexander'), 'western', true),
  ('Alexandra', public.normalize_chat_name('Alexandra'), 'western', true),
  ('Alexandre', public.normalize_chat_name('Alexandre'), 'western', true),
  ('Alice', public.normalize_chat_name('Alice'), 'western', true),
  ('Amanda', public.normalize_chat_name('Amanda'), 'western', true),
  ('Amber', public.normalize_chat_name('Amber'), 'western', true),
  ('Amelie', public.normalize_chat_name('Amelie'), 'western', true),
  ('Amira', public.normalize_chat_name('Amira'), 'international', true),
  ('Amy', public.normalize_chat_name('Amy'), 'western', true),
  ('Andre', public.normalize_chat_name('Andre'), 'western', true),
  ('Andrew', public.normalize_chat_name('Andrew'), 'western', true),
  ('Andy', public.normalize_chat_name('Andy'), 'western', true),
  ('Angela', public.normalize_chat_name('Angela'), 'western', true),
  ('Angelina', public.normalize_chat_name('Angelina'), 'western', true),
  ('Anna', public.normalize_chat_name('Anna'), 'western', true),
  ('Annie', public.normalize_chat_name('Annie'), 'western', true),
  ('Annette', public.normalize_chat_name('Annette'), 'western', true),
  ('Annika', public.normalize_chat_name('Annika'), 'western', true),
  ('Anthony', public.normalize_chat_name('Anthony'), 'western', true),
  ('Anushka', public.normalize_chat_name('Anushka'), 'international', true),
  ('Anya', public.normalize_chat_name('Anya'), 'international', true),
  ('Ariana', public.normalize_chat_name('Ariana'), 'western', true),
  ('Armand', public.normalize_chat_name('Armand'), 'western', true),
  ('Arthur', public.normalize_chat_name('Arthur'), 'western', true),
  ('Ashley', public.normalize_chat_name('Ashley'), 'western', true),
  ('Ashton', public.normalize_chat_name('Ashton'), 'western', true),
  ('Astrid', public.normalize_chat_name('Astrid'), 'western', true),
  ('Audrey', public.normalize_chat_name('Audrey'), 'western', true),
  ('August', public.normalize_chat_name('August'), 'western', true),
  ('Aurora', public.normalize_chat_name('Aurora'), 'western', true),
  ('Austin', public.normalize_chat_name('Austin'), 'western', true),
  ('Babette', public.normalize_chat_name('Babette'), 'western', true),
  ('Barb', public.normalize_chat_name('Barb'), 'western', true),
  ('Barbra', public.normalize_chat_name('Barbra'), 'western', true),
  ('Barry', public.normalize_chat_name('Barry'), 'western', true),
  ('Beatrix', public.normalize_chat_name('Beatrix'), 'western', true),
  ('Bella', public.normalize_chat_name('Bella'), 'western', true),
  ('Ben', public.normalize_chat_name('Ben'), 'western', true),
  ('Bette', public.normalize_chat_name('Bette'), 'western', true),
  ('Betty', public.normalize_chat_name('Betty'), 'western', true),
  ('Bill', public.normalize_chat_name('Bill'), 'western', true),
  ('Billie', public.normalize_chat_name('Billie'), 'western', true),
  ('Billy', public.normalize_chat_name('Billy'), 'western', true),
  ('Bjork', public.normalize_chat_name('Bjork'), 'western', true),
  ('Blake', public.normalize_chat_name('Blake'), 'western', true),
  ('Bobby', public.normalize_chat_name('Bobby'), 'western', true),
  ('Boyan', public.normalize_chat_name('Boyan'), 'international', true),
  ('Brad', public.normalize_chat_name('Brad'), 'western', true),
  ('Bradley', public.normalize_chat_name('Bradley'), 'western', true),
  ('Brandon', public.normalize_chat_name('Brandon'), 'western', true),
  ('Brandy', public.normalize_chat_name('Brandy'), 'western', true),
  ('Brennan', public.normalize_chat_name('Brennan'), 'western', true),
  ('Brett', public.normalize_chat_name('Brett'), 'western', true),
  ('Brian', public.normalize_chat_name('Brian'), 'western', true),
  ('Brigitte', public.normalize_chat_name('Brigitte'), 'western', true),
  ('Britney', public.normalize_chat_name('Britney'), 'western', true),
  ('Britta', public.normalize_chat_name('Britta'), 'western', true),
  ('Brittany', public.normalize_chat_name('Brittany'), 'western', true),
  ('Brooke', public.normalize_chat_name('Brooke'), 'western', true),
  ('Bruce', public.normalize_chat_name('Bruce'), 'western', true),
  ('Bruno', public.normalize_chat_name('Bruno'), 'western', true),
  ('Bryson', public.normalize_chat_name('Bryson'), 'western', true),
  ('Caleb', public.normalize_chat_name('Caleb'), 'western', true),
  ('Calvin', public.normalize_chat_name('Calvin'), 'western', true),
  ('Cameron', public.normalize_chat_name('Cameron'), 'western', true),
  ('Camila', public.normalize_chat_name('Camila'), 'international', true),
  ('Cara', public.normalize_chat_name('Cara'), 'western', true),
  ('Carl', public.normalize_chat_name('Carl'), 'western', true),
  ('Carli', public.normalize_chat_name('Carli'), 'western', true),
  ('Carly', public.normalize_chat_name('Carly'), 'western', true),
  ('Caroline', public.normalize_chat_name('Caroline'), 'western', true),
  ('Carter', public.normalize_chat_name('Carter'), 'western', true),
  ('Cate', public.normalize_chat_name('Cate'), 'western', true),
  ('Catherine', public.normalize_chat_name('Catherine'), 'western', true),
  ('Cecil', public.normalize_chat_name('Cecil'), 'western', true),
  ('Celine', public.normalize_chat_name('Celine'), 'western', true),
  ('Chandler', public.normalize_chat_name('Chandler'), 'western', true),
  ('Chan', public.normalize_chat_name('Chan'), 'international', true),
  ('Chang', public.normalize_chat_name('Chang'), 'international', true),
  ('Charles', public.normalize_chat_name('Charles'), 'western', true),
  ('Charlize', public.normalize_chat_name('Charlize'), 'western', true),
  ('Charli', public.normalize_chat_name('Charli'), 'western', true),
  ('Charlie', public.normalize_chat_name('Charlie'), 'western', true),
  ('Charmaine', public.normalize_chat_name('Charmaine'), 'western', true),
  ('Charlotte', public.normalize_chat_name('Charlotte'), 'western', true),
  ('Chase', public.normalize_chat_name('Chase'), 'western', true),
  ('Chloe', public.normalize_chat_name('Chloe'), 'western', true),
  ('Chris', public.normalize_chat_name('Chris'), 'western', true),
  ('Christian', public.normalize_chat_name('Christian'), 'western', true),
  ('Christina', public.normalize_chat_name('Christina'), 'western', true),
  ('Christopher', public.normalize_chat_name('Christopher'), 'western', true),
  ('Ciara', public.normalize_chat_name('Ciara'), 'western', true),
  ('Cillian', public.normalize_chat_name('Cillian'), 'western', true),
  ('Cindy', public.normalize_chat_name('Cindy'), 'western', true),
  ('Clair', public.normalize_chat_name('Clair'), 'western', true),
  ('Clark', public.normalize_chat_name('Clark'), 'western', true),
  ('Claude', public.normalize_chat_name('Claude'), 'western', true),
  ('Claudia', public.normalize_chat_name('Claudia'), 'western', true),
  ('Clint', public.normalize_chat_name('Clint'), 'western', true),
  ('Clive', public.normalize_chat_name('Clive'), 'western', true),
  ('Cobie', public.normalize_chat_name('Cobie'), 'western', true),
  ('Coco', public.normalize_chat_name('Coco'), 'western', true),
  ('Cole', public.normalize_chat_name('Cole'), 'western', true),
  ('Colin', public.normalize_chat_name('Collin'), 'western', true),
  ('Colton', public.normalize_chat_name('Colton'), 'western', true),
  ('Cooper', public.normalize_chat_name('Cooper'), 'western', true),
  ('Courtney', public.normalize_chat_name('Courtney'), 'western', true),
  ('Craig', public.normalize_chat_name('Craig'), 'western', true),
  ('Crystal', public.normalize_chat_name('Crystal'), 'western', true),
  ('Dacre', public.normalize_chat_name('Dacre'), 'western', true),
  ('Daisy', public.normalize_chat_name('Daisy'), 'western', true),
  ('Dakota', public.normalize_chat_name('Dakota'), 'western', true),
  ('Damien', public.normalize_chat_name('Damien'), 'western', true),
  ('Damon', public.normalize_chat_name('Damon'), 'western', true),
  ('Dan', public.normalize_chat_name('Dan'), 'western', true),
  ('Dana', public.normalize_chat_name('Dana'), 'western', true),
  ('Dane', public.normalize_chat_name('Dane'), 'western', true),
  ('Daniel', public.normalize_chat_name('Daniel'), 'western', true),
  ('Danielle', public.normalize_chat_name('Danielle'), 'western', true),
  ('Danny', public.normalize_chat_name('Danny'), 'western', true),
  ('Dante', public.normalize_chat_name('Dante'), 'international', true),
  ('Dasha', public.normalize_chat_name('Dasha'), 'international', true),
  ('Dave', public.normalize_chat_name('Dave'), 'western', true),
  ('David', public.normalize_chat_name('David'), 'western', true),
  ('Dawn', public.normalize_chat_name('Dawn'), 'western', true),
  ('Demi', public.normalize_chat_name('Demi'), 'western', true),
  ('Dennis', public.normalize_chat_name('Dennis'), 'western', true),
  ('Denzel', public.normalize_chat_name('Denzel'), 'western', true),
  ('Derek', public.normalize_chat_name('Derek'), 'western', true),
  ('Derrick', public.normalize_chat_name('Derrick'), 'western', true),
  ('Desi', public.normalize_chat_name('Desi'), 'international', true),
  ('Dev', public.normalize_chat_name('Dev'), 'international', true),
  ('Diaz', public.normalize_chat_name('Diaz'), 'international', true),
  ('Dillon', public.normalize_chat_name('Dillon'), 'western', true),
  ('Dylan', public.normalize_chat_name('Dylan'), 'western', true),
  ('Dimitri', public.normalize_chat_name('Dimitri'), 'international', true),
  ('Diane', public.normalize_chat_name('Diane'), 'western', true),
  ('Diana', public.normalize_chat_name('Diana'), 'western', true),
  ('Dirk', public.normalize_chat_name('Dirk'), 'western', true),
  ('Dmitri', public.normalize_chat_name('Dmitri'), 'international', true),
  ('Dolly', public.normalize_chat_name('Dolly'), 'western', true),
  ('Dominic', public.normalize_chat_name('Dominic'), 'western', true),
  ('Donnie', public.normalize_chat_name('Donnie'), 'western', true),
  ('Douglas', public.normalize_chat_name('Douglas'), 'western', true),
  ('Drake', public.normalize_chat_name('Drake'), 'western', true),
  ('Drew', public.normalize_chat_name('Drew'), 'western', true),
  ('Duncan', public.normalize_chat_name('Duncan'), 'western', true),
  ('Dwayne', public.normalize_chat_name('Dwayne'), 'western', true),
  ('Eddie', public.normalize_chat_name('Eddie'), 'western', true),
  ('Edwards', public.normalize_chat_name('Edwards'), 'western', true),
  ('Elena', public.normalize_chat_name('Elena'), 'western', true),
  ('Eli', public.normalize_chat_name('Eli'), 'western', true),
  ('Elizabeth', public.normalize_chat_name('Elizabeth'), 'western', true),
  ('Ellen', public.normalize_chat_name('Ellen'), 'western', true),
  ('Elton', public.normalize_chat_name('Elton'), 'western', true),
  ('Elvis', public.normalize_chat_name('Elvis'), 'western', true),
  ('Emily', public.normalize_chat_name('Emily'), 'western', true),
  ('Emilio', public.normalize_chat_name('Emilio'), 'international', true),
  ('Emma', public.normalize_chat_name('Emma'), 'western', true),
  ('Enid', public.normalize_chat_name('Enid'), 'western', true),
  ('Enzo', public.normalize_chat_name('Enzo'), 'international', true),
  ('Erica', public.normalize_chat_name('Erica'), 'western', true),
  ('Erik', public.normalize_chat_name('Erik'), 'western', true),
  ('Erin', public.normalize_chat_name('Erin'), 'western', true),
  ('Estelle', public.normalize_chat_name('Estelle'), 'western', true),
  ('Eugene', public.normalize_chat_name('Eugene'), 'western', true),
  ('Evan', public.normalize_chat_name('Evan'), 'western', true),
  ('Evangeline', public.normalize_chat_name('Evangeline'), 'western', true),
  ('Ezra', public.normalize_chat_name('Ezra'), 'western', true),
  ('Faye', public.normalize_chat_name('Faye'), 'western', true),
  ('Fergie', public.normalize_chat_name('Fergie'), 'western', true),
  ('Finn', public.normalize_chat_name('Finn'), 'western', true),
  ('Fiona', public.normalize_chat_name('Fiona'), 'western', true),
  ('Florence', public.normalize_chat_name('Florence'), 'western', true),
  ('Flynn', public.normalize_chat_name('Flynn'), 'western', true),
  ('Frances', public.normalize_chat_name('Frances'), 'western', true),
  ('Francis', public.normalize_chat_name('Francis'), 'western', true),
  ('Frank', public.normalize_chat_name('Frank'), 'western', true),
  ('Frankie', public.normalize_chat_name('Frankie'), 'western', true),
  ('Franz', public.normalize_chat_name('Franz'), 'western', true),
  ('Fred', public.normalize_chat_name('Fred'), 'western', true),
  ('Freddie', public.normalize_chat_name('Freddie'), 'western', true),
  ('Frida', public.normalize_chat_name('Frida'), 'international', true),
  ('Gabriel', public.normalize_chat_name('Gabriel'), 'western', true),
  ('Gaten', public.normalize_chat_name('Gaten'), 'western', true),
  ('Geena', public.normalize_chat_name('Geena'), 'western', true),
  ('Geoffrey', public.normalize_chat_name('Geoffrey'), 'western', true),
  ('George', public.normalize_chat_name('George'), 'western', true),
  ('Georgia', public.normalize_chat_name('Georgia'), 'western', true),
  ('Giannis', public.normalize_chat_name('Giannis'), 'international', true),
  ('Gigi', public.normalize_chat_name('Gigi'), 'western', true),
  ('Ginger', public.normalize_chat_name('Ginger'), 'western', true),
  ('Ginny', public.normalize_chat_name('Ginny'), 'western', true),
  ('Gisele', public.normalize_chat_name('Gisele'), 'international', true),
  ('Glenn', public.normalize_chat_name('Glenn'), 'western', true),
  ('Gordon', public.normalize_chat_name('Gordon'), 'western', true),
  ('Grace', public.normalize_chat_name('Grace'), 'western', true),
  ('Grant', public.normalize_chat_name('Grant'), 'western', true),
  ('Greg', public.normalize_chat_name('Greg'), 'western', true),
  ('Gregory', public.normalize_chat_name('Gregory'), 'western', true),
  ('Greta', public.normalize_chat_name('Greta'), 'western', true),
  ('Gustav', public.normalize_chat_name('Gustav'), 'western', true),
  ('Gustavo', public.normalize_chat_name('Gustavo'), 'international', true),
  ('Gwen', public.normalize_chat_name('Gwen'), 'western', true),
  ('Hadfield', public.normalize_chat_name('Hadfield'), 'western', true),
  ('Haley', public.normalize_chat_name('Haley'), 'western', true),
  ('Haliburton', public.normalize_chat_name('Haliburton'), 'western', true),
  ('Halsey', public.normalize_chat_name('Halsey'), 'western', true),
  ('Hana', public.normalize_chat_name('Hana'), 'international', true),
  ('Hank', public.normalize_chat_name('Hank'), 'western', true),
  ('Hanna', public.normalize_chat_name('Hannah'), 'western', true),
  ('Hans', public.normalize_chat_name('Hans'), 'western', true),
  ('Hardy', public.normalize_chat_name('Hardy'), 'western', true),
  ('Harold', public.normalize_chat_name('Harold'), 'western', true),
  ('Harriet', public.normalize_chat_name('Harriet'), 'western', true),
  ('Harris', public.normalize_chat_name('Harris'), 'western', true),
  ('Harrison', public.normalize_chat_name('Harrison'), 'western', true),
  ('Harry', public.normalize_chat_name('Harry'), 'western', true),
  ('Harvey', public.normalize_chat_name('Harvey'), 'western', true),
  ('Hazel', public.normalize_chat_name('Hazel'), 'western', true),
  ('Heath', public.normalize_chat_name('Heath'), 'western', true),
  ('Heather', public.normalize_chat_name('Heather'), 'western', true),
  ('Heidi', public.normalize_chat_name('Heidi'), 'western', true),
  ('Helen', public.normalize_chat_name('Helen'), 'western', true),
  ('Helena', public.normalize_chat_name('Helena'), 'western', true),
  ('Henri', public.normalize_chat_name('Henri'), 'western', true),
  ('Henry', public.normalize_chat_name('Henry'), 'western', true),
  ('Hideki', public.normalize_chat_name('Hideki'), 'international', true),
  ('Hilary', public.normalize_chat_name('Hilary'), 'western', true),
  ('Holly', public.normalize_chat_name('Holly'), 'western', true),
  ('Hugh', public.normalize_chat_name('Hugh'), 'western', true),
  ('Hunter', public.normalize_chat_name('Hunter'), 'western', true),
  ('Ian', public.normalize_chat_name('Ian'), 'western', true),
  ('Ibrahim', public.normalize_chat_name('Ibrahim'), 'international', true),
  ('Idris', public.normalize_chat_name('Idris'), 'international', true),
  ('Ilya', public.normalize_chat_name('Ilya'), 'international', true),
  ('Iman', public.normalize_chat_name('Iman'), 'international', true),
  ('Ingrid', public.normalize_chat_name('Ingrid'), 'western', true),
  ('Ira', public.normalize_chat_name('Ira'), 'western', true),
  ('Irina', public.normalize_chat_name('Irina'), 'international', true),
  ('Isaac', public.normalize_chat_name('Isaac'), 'western', true),
  ('Jack', public.normalize_chat_name('Jack'), 'western', true),
  ('Jackie', public.normalize_chat_name('Jackie'), 'western', true),
  ('Jacob', public.normalize_chat_name('Jacob'), 'western', true),
  ('Jaden', public.normalize_chat_name('Jaden'), 'western', true),
  ('James', public.normalize_chat_name('James'), 'western', true),
  ('Jamie', public.normalize_chat_name('Jamie'), 'western', true),
  ('Jane', public.normalize_chat_name('Jane'), 'western', true),
  ('Janet', public.normalize_chat_name('Janet'), 'western', true),
  ('Janice', public.normalize_chat_name('Janice'), 'western', true),
  ('Janis', public.normalize_chat_name('Janis'), 'western', true),
  ('Jared', public.normalize_chat_name('Jared'), 'western', true),
  ('Jason', public.normalize_chat_name('Jason'), 'western', true),
  ('Jay', public.normalize_chat_name('Jay'), 'western', true),
  ('Jenna', public.normalize_chat_name('Jenna'), 'western', true),
  ('Jennifer', public.normalize_chat_name('Jennifer'), 'western', true),
  ('Jerry', public.normalize_chat_name('Jerry'), 'western', true),
  ('Jess', public.normalize_chat_name('Jess'), 'western', true),
  ('Jesse', public.normalize_chat_name('Jesse'), 'western', true),
  ('Jessica', public.normalize_chat_name('Jessica'), 'western', true),
  ('Jimi', public.normalize_chat_name('Jimi'), 'western', true),
  ('Jimmy', public.normalize_chat_name('Jimmy'), 'western', true),
  ('Joan', public.normalize_chat_name('Joan'), 'western', true),
  ('Joaquin', public.normalize_chat_name('Joaquin'), 'international', true),
  ('Jodie', public.normalize_chat_name('Jodie'), 'western', true),
  ('Joe', public.normalize_chat_name('Joe'), 'western', true),
  ('Joel', public.normalize_chat_name('Joel'), 'western', true),
  ('Joey', public.normalize_chat_name('Joey'), 'western', true),
  ('John', public.normalize_chat_name('John'), 'western', true),
  ('Johnny', public.normalize_chat_name('Johnny'), 'western', true),
  ('Jon', public.normalize_chat_name('Jon'), 'western', true),
  ('Jonah', public.normalize_chat_name('Jonah'), 'western', true),
  ('Jonathan', public.normalize_chat_name('Jonathan'), 'western', true),
  ('Jordan', public.normalize_chat_name('Jordan'), 'western', true),
  ('Joseph', public.normalize_chat_name('Joseph'), 'western', true),
  ('Josh', public.normalize_chat_name('Josh'), 'western', true),
  ('Joshua', public.normalize_chat_name('Joshua'), 'western', true),
  ('Jules', public.normalize_chat_name('Jules'), 'western', true),
  ('Julia', public.normalize_chat_name('Julia'), 'western', true),
  ('Julian', public.normalize_chat_name('Julian'), 'western', true),
  ('Julianne', public.normalize_chat_name('Julianne'), 'western', true),
  ('Julius', public.normalize_chat_name('Julius'), 'western', true),
  ('Jurgen', public.normalize_chat_name('Jurgen'), 'western', true),
  ('Justin', public.normalize_chat_name('Justin'), 'western', true)
on conflict (normalized_name) do update
set base_name = excluded.base_name,
    region_group = excluded.region_group,
    is_active = true;

create or replace function public.pick_chat_base_name(p_artist_name text)
returns table (
  base_name text,
  normalized_name text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  target_region text;
  artist_normalized text;
  eligible_count integer;
  selected_offset integer;
  selected_pool_id bigint;
begin
  target_region := case when random() < 0.7 then 'western' else 'international' end;
  artist_normalized := public.normalize_chat_name(p_artist_name);

  select count(*)::integer
  into eligible_count
  from public.chat_name_pool pool
  where pool.is_active
    and pool.region_group = target_region
    and pool.normalized_name not in ('admin', 'administrator', 'artist', 'moderator', 'mod', 'official', 'system', 'support')
    and pool.normalized_name <> artist_normalized
    and not exists (
      select 1
      from public.chat_name_pool_exclusions excluded
      where excluded.normalized_name = pool.normalized_name
    );

  if eligible_count > 0 then
    selected_offset := floor(random() * eligible_count)::integer;

    select pool.id, pool.base_name, pool.normalized_name
    into selected_pool_id, base_name, normalized_name
    from public.chat_name_pool pool
    where pool.is_active
      and pool.region_group = target_region
      and pool.normalized_name not in ('admin', 'administrator', 'artist', 'moderator', 'mod', 'official', 'system', 'support')
      and pool.normalized_name <> artist_normalized
      and not exists (
        select 1
        from public.chat_name_pool_exclusions excluded
        where excluded.normalized_name = pool.normalized_name
      )
    order by pool.id
    offset selected_offset
    limit 1;

    raise log 'chat_name_pick region=% eligible_count=% selected_pool_id=% suffix_added=%', target_region, eligible_count, selected_pool_id, false;
    return next;
    return;
  end if;

  select count(*)::integer
  into eligible_count
  from public.chat_name_pool pool
  where pool.is_active
    and pool.normalized_name not in ('admin', 'administrator', 'artist', 'moderator', 'mod', 'official', 'system', 'support')
    and pool.normalized_name <> artist_normalized
    and not exists (
      select 1
      from public.chat_name_pool_exclusions excluded
      where excluded.normalized_name = pool.normalized_name
    );

  if eligible_count <= 0 then
    return;
  end if;

  selected_offset := floor(random() * eligible_count)::integer;

  select pool.id, pool.base_name, pool.normalized_name
  into selected_pool_id, base_name, normalized_name
  from public.chat_name_pool pool
  where pool.is_active
    and pool.normalized_name not in ('admin', 'administrator', 'artist', 'moderator', 'mod', 'official', 'system', 'support')
    and pool.normalized_name <> artist_normalized
    and not exists (
      select 1
      from public.chat_name_pool_exclusions excluded
      where excluded.normalized_name = pool.normalized_name
    )
  order by pool.id
  offset selected_offset
  limit 1;

  raise log 'chat_name_pick region=% eligible_count=% selected_pool_id=% suffix_added=%', 'fallback', eligible_count, selected_pool_id, false;
  return next;
end;
$$;

revoke all on function public.pick_chat_base_name(text) from public;

drop function if exists public.join_event_chat(uuid, uuid);
drop function if exists public.chat_generated_first_names();

create or replace function public.join_event_chat(
  p_event_id uuid,
  p_session_id uuid
)
returns table (
  id uuid,
  event_id uuid,
  session_id uuid,
  display_name text,
  normalized_name text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  event_artist_name text;
  existing_participant public.event_chat_participants;
  inserted_participant public.event_chat_participants;
  base_name text;
  base_normalized text;
  candidate_name text;
  normalized_candidate text;
  existing_base_name text;
  should_reassign_existing boolean := false;
  attempt integer;
  suffix_number integer;
begin
  if p_event_id is null then
    raise exception 'chat_event_required';
  end if;

  if p_session_id is null then
    raise exception 'chat_session_required';
  end if;

  select events.artist_name
  into event_artist_name
  from public.events
  where events.id = p_event_id
    and events.status in ('upcoming', 'live')
    and events.starts_at is not null
    and events.ends_at is not null
    and events.starts_at <= now()
    and events.ends_at > now();

  if event_artist_name is null then
    raise exception 'chat_event_not_live';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_event_id::text || ':' || p_session_id::text));

  select *
  into existing_participant
  from public.event_chat_participants
  where event_chat_participants.event_id = p_event_id
    and event_chat_participants.session_id = p_session_id
  limit 1;

  if existing_participant.id is not null then
    existing_base_name := regexp_replace(existing_participant.display_name, '[0-9]+$', '');

    if exists (
      select 1
      from public.chat_name_pool pool
      where pool.is_active = true
        and pool.normalized_name = public.normalize_chat_name(existing_base_name)
    ) then
      return query
        select
          existing_participant.id,
          existing_participant.event_id,
          existing_participant.session_id,
          existing_participant.display_name,
          existing_participant.normalized_name,
          existing_participant.created_at;
      return;
    end if;

    should_reassign_existing := true;
  end if;

  if existing_participant.id is not null and should_reassign_existing = false then
    return query
      select
        existing_participant.id,
        existing_participant.event_id,
        existing_participant.session_id,
        existing_participant.display_name,
        existing_participant.normalized_name,
        existing_participant.created_at;
    return;
  end if;

  for attempt in 1..25 loop
    select picked.base_name, picked.normalized_name
    into base_name, base_normalized
    from public.pick_chat_base_name(event_artist_name) picked
    limit 1;

    if base_name is null then
      raise exception 'chat_name_pool_empty';
    end if;

    perform pg_advisory_xact_lock(hashtext(p_event_id::text || ':' || base_normalized));

    for suffix_number in 1..50 loop
      if suffix_number = 1 then
        candidate_name := left(base_name, 16);
      else
        candidate_name := left(base_name, greatest(1, 16 - char_length(suffix_number::text))) || suffix_number::text;
        raise log 'chat_name_suffix base_name=% suffix_number=% suffix_added=%', base_name, suffix_number, true;
      end if;

      normalized_candidate := public.normalize_chat_name(candidate_name);

      if normalized_candidate in ('admin', 'administrator', 'artist', 'moderator', 'mod', 'official', 'system', 'support') then
        continue;
      end if;

      if normalized_candidate = public.normalize_chat_name(event_artist_name) then
        continue;
      end if;

      begin
        if should_reassign_existing then
          update public.event_chat_participants
          set display_name = candidate_name,
              normalized_name = normalized_candidate
          where event_chat_participants.id = existing_participant.id
          returning * into inserted_participant;
        else
          insert into public.event_chat_participants (
            event_id,
            session_id,
            display_name,
            normalized_name
          )
          values (
            p_event_id,
            p_session_id,
            candidate_name,
            normalized_candidate
          )
          returning * into inserted_participant;
        end if;

        return query
          select
            inserted_participant.id,
            inserted_participant.event_id,
            inserted_participant.session_id,
            inserted_participant.display_name,
            inserted_participant.normalized_name,
            inserted_participant.created_at;
        return;
      exception
        when unique_violation then
          select *
          into existing_participant
          from public.event_chat_participants
          where event_chat_participants.event_id = p_event_id
            and event_chat_participants.session_id = p_session_id
          limit 1;

          if existing_participant.id is not null and should_reassign_existing = false then
            return query
              select
                existing_participant.id,
                existing_participant.event_id,
                existing_participant.session_id,
                existing_participant.display_name,
                existing_participant.normalized_name,
                existing_participant.created_at;
            return;
          end if;
      end;
    end loop;
  end loop;

  raise exception 'chat_name_allocation_failed';
end;
$$;

revoke all on function public.join_event_chat(uuid, uuid) from public;
grant execute on function public.join_event_chat(uuid, uuid) to anon, authenticated;

notify pgrst, 'reload schema';
