-- Step 4 curated live-chat deterministic risk classification.

alter table public.chat_messages
add column if not exists risk_level text,
add column if not exists risk_score integer,
add column if not exists risk_flags text[] not null default array[]::text[],
add column if not exists classified_at timestamptz,
add column if not exists classifier_version text,
add column if not exists auto_publish_eligible boolean not null default false,
add column if not exists rejection_source text;

alter table public.chat_messages
drop constraint if exists chat_messages_risk_level_check;

alter table public.chat_messages
add constraint chat_messages_risk_level_check
check (risk_level is null or risk_level in ('low', 'medium', 'high'));

alter table public.chat_messages
drop constraint if exists chat_messages_risk_score_check;

alter table public.chat_messages
add constraint chat_messages_risk_score_check
check (risk_score is null or (risk_score >= 0 and risk_score <= 100));

alter table public.chat_message_moderation_audit
drop constraint if exists chat_message_moderation_audit_action_check;

alter table public.chat_message_moderation_audit
add constraint chat_message_moderation_audit_action_check
check (action in ('message_approved', 'message_rejected', 'message_classified', 'message_auto_rejected'));

alter table public.chat_message_moderation_audit
add column if not exists participant_id uuid references public.event_chat_participants(id) on delete set null,
add column if not exists risk_level text,
add column if not exists risk_flags text[],
add column if not exists classifier_version text;

alter table public.chat_message_moderation_audit enable row level security;
revoke all on table public.chat_message_moderation_audit from anon, authenticated;
grant select on table public.chat_message_moderation_audit to authenticated;

drop policy if exists "Owners can read chat moderation audit rows" on public.chat_message_moderation_audit;
create policy "Owners can read chat moderation audit rows"
on public.chat_message_moderation_audit
for select
to authenticated
using (
  exists (
    select 1
    from public.events
    where events.id = chat_message_moderation_audit.event_id
      and events.owner_id = auth.uid()
  )
);

create index if not exists chat_messages_event_participant_created_idx
on public.chat_messages(event_id, participant_id, created_at desc)
where event_id is not null
  and participant_id is not null;

create table if not exists public.chat_risk_terms (
  id bigint generated by default as identity primary key,
  term text not null,
  normalized_term text not null,
  match_mode text not null default 'substring' check (match_mode in ('exact', 'substring', 'word')),
  risk text not null check (risk in ('review', 'hard')),
  flag text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint chat_risk_terms_term_not_empty check (char_length(btrim(term)) > 0)
);

alter table public.chat_risk_terms
drop constraint if exists chat_risk_terms_match_mode_check;

alter table public.chat_risk_terms
add constraint chat_risk_terms_match_mode_check
check (match_mode in ('exact', 'substring', 'word'));

create unique index if not exists chat_risk_terms_normalized_mode_risk_idx
on public.chat_risk_terms(normalized_term, match_mode, risk, flag);

alter table public.chat_risk_terms enable row level security;
revoke select, insert, update, delete, truncate on public.chat_risk_terms from anon, authenticated;

insert into public.chat_risk_terms (term, normalized_term, match_mode, risk, flag)
values
  ('kill yourself', 'kill yourself', 'substring', 'hard', 'THREAT'),
  ('go die', 'go die', 'substring', 'hard', 'THREAT'),
  ('i hope you die', 'i hope you die', 'substring', 'hard', 'THREAT'),
  ('kys', 'kys', 'exact', 'hard', 'THREAT'),
  ('test-hate-speech-term', 'test-hate-speech-term', 'exact', 'hard', 'HATE_SPEECH'),
  ('fuck', 'fuck', 'word', 'review', 'PROFANITY'),
  ('shit', 'shit', 'word', 'review', 'PROFANITY'),
  ('bitch', 'bitch', 'word', 'review', 'PROFANITY'),
  ('asshole', 'asshole', 'word', 'review', 'PROFANITY'),
  ('official admin announcement', 'official admin announcement', 'substring', 'review', 'ADMIN_IMPERSONATION'),
  ('moderator here', 'moderator here', 'substring', 'review', 'ADMIN_IMPERSONATION')
on conflict (normalized_term, match_mode, risk, flag) do nothing;

create or replace function public.normalize_chat_body_for_risk(p_body text)
returns text
language sql
immutable
set search_path = public
as $$
  select lower(btrim(regexp_replace(coalesce(p_body, ''), '\s+', ' ', 'g')));
$$;

create or replace function public.chat_message_risk_classifier_version()
returns text
language sql
immutable
as $$
  select 'rules-v1';
$$;

create or replace function public.classify_chat_message(
  p_event_id uuid,
  p_participant_id uuid,
  p_message_id uuid,
  p_body text
)
returns jsonb
language plpgsql
stable
set search_path = public
as $$
declare
  clean_body text := coalesce(p_body, '');
  comparison_body text := public.normalize_chat_body_for_risk(p_body);
  score integer := 0;
  flags text[] := array[]::text[];
  force_high boolean := false;
  duplicate_count integer := 0;
  alpha_count integer := 0;
  upper_count integer := 0;
  mention_count integer := 0;
  term_record record;
  risk_level text;
  event_artist_name text := '';
begin
  select public.normalize_chat_body_for_risk(artist_name)
  into event_artist_name
  from public.events
  where id = p_event_id;

  mention_count := length(clean_body) - length(replace(clean_body, '@', ''));

  if clean_body ~* '(javascript|data|file)\s*:' then
    flags := array_append(flags, 'UNSAFE_PROTOCOL');
    force_high := true;
  end if;

  if clean_body ~* '(https?://|www\.)'
    or comparison_body ~ '(^|[^[:alnum:]_@-])([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+(com|org|net|edu|gov|io|co|uk|de|fr|it|es|nl|be|ch|at|se|no|dk|fi|pl|cz|ca|us|au|nz|jp|kr|cn|in|br|mx|tv|fm|me|app|dev|gg|ly|cloud|info|biz|xyz|shop|store|music|social)([/:?#][^[:space:]]*)?([^[:alnum:]_]|$)' then
    flags := array_append(flags, 'CONTAINS_LINK');
    score := score + 25;
  end if;

  if comparison_body ~ '(follow me|follow my|follow @[a-z0-9_\.]|subscribe to me|subscribe to my|check my page|check my profile|check out my account|check my account)' then
    flags := array_append(flags, 'FOLLOW_SOLICITATION');
    score := score + 25;
  end if;

  if comparison_body ~ '(dm me|dm @[a-z0-9_\.]|message me|message me on|contact me|add me|add me on|send me a dm|hit me up|join my|join the discord|my insta is|my instagram is|my ig is|my snap is|my snapchat is|my telegram is)' then
    flags := array_append(flags, 'CONTACT_SOLICITATION');
    score := score + 25;
  end if;

  if comparison_body ~ '(follow me|follow my|follow @[a-z0-9_\.]|subscribe to me|subscribe to my|dm me|dm @[a-z0-9_\.]|message me|message me on|contact me|add me|add me on|send me a dm|hit me up|join my|check my page|check my profile|check out my account|check my account|my (insta|instagram|ig|snap|snapchat|telegram) is)'
    and comparison_body ~ '(^|[^a-z0-9])(instagram|insta|ig|tiktok|tik tok|twitter|snapchat|snap|discord|telegram|twitch|youtube|yt|soundcloud|spotify|facebook|fb)([^a-z0-9]|$)|@[a-z0-9]' then
    flags := array_append(flags, 'SOCIAL_PROMOTION');
    score := score + 10;
  end if;

  if comparison_body ~ '(^|[[:space:][:punct:]])@[a-z0-9][a-z0-9._]{1,28}[a-z0-9]([^a-z0-9._]|$)'
    and (
      comparison_body ~ '(follow me|follow my|follow @[a-z0-9_\.]|subscribe to me|subscribe to my|dm me|dm @[a-z0-9_\.]|message me|message me on|contact me|add me|add me on|send me a dm|hit me up|join my|check my page|check my profile|check out my account|check my account|my insta is|my instagram is|my ig is|my snap is|my snapchat is|my telegram is)'
      or comparison_body ~ '(^|[^a-z0-9])(instagram|insta|ig|tiktok|tik tok|twitter|snapchat|snap|discord|telegram|twitch|youtube|yt|soundcloud|spotify|facebook|fb)([^a-z0-9]|$)'
    ) then
    flags := array_append(flags, 'SOCIAL_HANDLE');
    score := score + 15;
  end if;

  if clean_body ~* '([a-z0-9-]+\s*(\[dot\]|\(dot\)| dot )\s*[a-z]{2,})' then
    flags := array_append(flags, 'OBFUSCATED_LINK');
    score := score + 20;
  end if;

  if clean_body ~* '(<\s*script|<\s*iframe|onerror\s*=|onclick\s*=|javascript\s*:)' then
    flags := array_append(flags, 'SCRIPT_PAYLOAD');
    force_high := true;
  end if;

  if position(U&'\202A' in clean_body) > 0
    or position(U&'\202B' in clean_body) > 0
    or position(U&'\202D' in clean_body) > 0
    or position(U&'\202E' in clean_body) > 0
    or position(U&'\2066' in clean_body) > 0
    or position(U&'\2067' in clean_body) > 0
    or position(U&'\2068' in clean_body) > 0 then
    flags := array_append(flags, 'BIDI_CONTROL_ABUSE');
    force_high := true;
  end if;

  if comparison_body ~ '(kill yourself|go die|i hope you die|i(''m| am|m) going to kill you)' then
    flags := array_append(flags, 'THREAT');
    force_high := true;
  end if;

  if comparison_body ~ '(fuck you|shut the fuck up|you suck|you fucking suck|you(''re| are|re) (annoying|stupid|a fucking idiot|an idiot|idiot|trash)|i hate you|nobody likes you|what an idiot)' then
    flags := array_append(flags, 'PERSONAL_ATTACK');
    score := score + 30;
  end if;

  if comparison_body ~ '(this artist sucks|the artist sucks|artist is trash|artist is fucking trash|this artist is trash|this artist is fucking trash|worst singer ever|the singer is terrible|singer is terrible|the performer is terrible|performer is trash)'
    or (
      coalesce(event_artist_name, '') <> ''
      and (
        position(event_artist_name || ' sucks' in comparison_body) > 0
        or position(event_artist_name || ' is trash' in comparison_body) > 0
        or position(event_artist_name || ' is terrible' in comparison_body) > 0
      )
    ) then
    flags := array_append(flags, 'HARASSMENT');
    score := score + 30;
  end if;

  if comparison_body ~ '(you suck|you(''re| are|re) (annoying|stupid|an idiot|idiot|trash)|i hate you|nobody likes you)'
    and comparison_body ~ '(fuck|shit|bitch|asshole)' then
    score := score + 15;
  end if;

  if comparison_body ~ '(i am|i''m|im)\s+(the\s+)?official\s+artist'
    or comparison_body ~ 'official\s+artist\s+announcement' then
    flags := array_append(flags, 'ARTIST_IMPERSONATION');
    force_high := true;
  elsif comparison_body ~ '(i am|i''m|im)\s+(an?\s+)?(admin|moderator)'
    or comparison_body ~ 'official\s+admin\s+announcement' then
    flags := array_append(flags, 'ADMIN_IMPERSONATION');
    force_high := true;
  end if;

  if comparison_body ~ '(crypto giveaway|free crypto|send (crypto|bitcoin|btc|ethereum|eth)|seed phrase|wallet seed|double your money|airdrop claim|claim your airdrop)' then
    flags := array_append(flags, 'SCAM');
    force_high := true;
  end if;

  for term_record in
    select *
    from public.chat_risk_terms
    where is_active = true
  loop
    if (
      term_record.match_mode = 'exact'
      and comparison_body = term_record.normalized_term
    ) or (
      term_record.match_mode = 'substring'
      and position(term_record.normalized_term in comparison_body) > 0
    ) or (
      term_record.match_mode = 'word'
      and comparison_body ~ ('(^|[^[:alnum:]_])' || term_record.normalized_term || '([^[:alnum:]_]|$)')
    ) then
      flags := array_append(flags, term_record.flag);
      if term_record.risk = 'hard' then
        force_high := true;
      elsif term_record.flag = 'PROFANITY' then
        score := score + 0;
      else
        score := score + 25;
      end if;
    end if;
  end loop;

  select count(*)::integer
  into duplicate_count
  from public.chat_messages
  where event_id = p_event_id
    and participant_id = p_participant_id
    and id <> p_message_id
    and is_admin = false
    and created_at > now() - interval '10 minutes'
    and public.normalize_chat_body_for_risk(body) = comparison_body;

  if duplicate_count >= 2 then
    flags := array_append(flags, 'REPEATED_DUPLICATE');
    score := score + 30;
  elsif duplicate_count = 1 then
    flags := array_append(flags, 'RECENT_DUPLICATE');
    score := score + 30;
  end if;

  score := least(score, 100);

  if not force_high
    and not (
      flags && array[
        'CONTAINS_LINK',
        'FOLLOW_SOLICITATION',
        'CONTACT_SOLICITATION',
        'SOCIAL_PROMOTION',
        'SOCIAL_HANDLE',
        'OBFUSCATED_LINK',
        'UNSAFE_PROTOCOL',
        'SCRIPT_PAYLOAD',
        'BIDI_CONTROL_ABUSE',
        'PERSONAL_ATTACK',
        'HARASSMENT',
        'THREAT',
        'ARTIST_IMPERSONATION',
        'ADMIN_IMPERSONATION',
        'RECENT_DUPLICATE',
        'REPEATED_DUPLICATE',
        'HATE_SPEECH'
      ]::text[]
    ) then
    score := least(score, 19);
  end if;

  if force_high or score >= 60 then
    risk_level := 'high';
    score := greatest(score, 60);
  elsif score >= 20 then
    risk_level := 'medium';
  else
    risk_level := 'low';
  end if;

  return jsonb_build_object(
    'riskLevel', risk_level,
    'riskScore', score,
    'riskFlags', coalesce((select array_agg(distinct risk_flag) from unnest(flags) as risk_flag(risk_flag)), array[]::text[]),
    'classifierVersion', public.chat_message_risk_classifier_version(),
    'autoPublishEligible', risk_level = 'low'
  );
end;
$$;

revoke all on function public.classify_chat_message(uuid, uuid, uuid, text) from public, anon, authenticated;

create or replace function public.chat_message_public_submission_payload(p_message public.chat_messages)
returns jsonb
language sql
stable
set search_path = public
as $$
  select jsonb_build_object(
    'id', p_message.id,
    'event_id', p_message.event_id,
    'participant_id', p_message.participant_id,
    'display_name', p_message.display_name,
    'body', p_message.body,
    'status', p_message.status,
    'client_token', p_message.client_token,
    'created_at', p_message.created_at,
    'published_at', p_message.published_at
  );
$$;

revoke all on function public.chat_message_public_submission_payload(public.chat_messages) from public, anon, authenticated;

drop function if exists public.submit_chat_message(uuid, text, text, uuid);
drop function if exists public.submit_chat_message(uuid, uuid, text, text, text, uuid);
drop function if exists public.submit_chat_message(uuid, uuid, text, uuid);
drop function if exists public.submit_chat_message(uuid, uuid, uuid, text, uuid);

create or replace function public.submit_chat_message(
  p_event_id uuid,
  p_participant_id uuid,
  p_session_id uuid,
  p_body text,
  p_client_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_body text;
  participant public.event_chat_participants;
  inserted_message public.chat_messages;
  existing_message public.chat_messages;
  recent_count integer;
  oldest_recent_at timestamptz;
  retry_after_seconds integer;
  classification jsonb;
  v_now timestamptz;
begin
  normalized_body := btrim(coalesce(p_body, ''));

  if p_event_id is null then
    return jsonb_build_object('ok', false, 'code', 'EVENT_NOT_LIVE', 'message', 'Chat is open only during a live event.');
  end if;

  if p_client_token is null then
    return jsonb_build_object('ok', false, 'code', 'MESSAGE_ALREADY_SUBMITTED', 'message', 'Message could not be submitted.');
  end if;

  if p_participant_id is null then
    return jsonb_build_object('ok', false, 'code', 'INVALID_PARTICIPANT', 'message', 'A reserved chat identity is required.');
  end if;

  if p_session_id is null then
    return jsonb_build_object('ok', false, 'code', 'INVALID_PARTICIPANT_SESSION', 'message', 'Your chat session could not be verified.');
  end if;

  if coalesce(p_body, '') ~ '[[:cntrl:]]' then
    return jsonb_build_object('ok', false, 'code', 'MESSAGE_INVALID_CHARACTERS', 'message', 'Message contains unsupported characters.');
  end if;

  if normalized_body = '' then
    return jsonb_build_object('ok', false, 'code', 'MESSAGE_EMPTY', 'message', 'Message cannot be empty.');
  end if;

  if char_length(normalized_body) > 400 then
    return jsonb_build_object('ok', false, 'code', 'MESSAGE_TOO_LONG', 'message', 'Message must be 400 characters or fewer.');
  end if;

  if not exists (
    select 1
    from public.events
    where events.id = p_event_id
      and events.status in ('upcoming', 'live')
      and events.starts_at is not null
      and events.ends_at is not null
      and events.starts_at <= now()
      and events.ends_at > now()
  ) then
    return jsonb_build_object('ok', false, 'code', 'EVENT_NOT_LIVE', 'message', 'Chat is open only during a live event.');
  end if;

  select *
  into participant
  from public.event_chat_participants
  where event_chat_participants.id = p_participant_id
    and event_chat_participants.event_id = p_event_id
    and event_chat_participants.session_id = p_session_id;

  if participant.id is null then
    return jsonb_build_object('ok', false, 'code', 'INVALID_PARTICIPANT_SESSION', 'message', 'Your chat session could not be verified.');
  end if;

  perform pg_advisory_xact_lock(hashtext(p_event_id::text || ':' || p_participant_id::text));

  select *
  into existing_message
  from public.chat_messages
  where chat_messages.event_id = p_event_id
    and chat_messages.participant_id = p_participant_id
    and chat_messages.client_token = p_client_token
  limit 1;

  if existing_message.id is not null then
    return jsonb_build_object('ok', true, 'duplicate', true, 'message', public.chat_message_public_submission_payload(existing_message));
  end if;

  select count(*)::integer, min(created_at)
  into recent_count, oldest_recent_at
  from public.chat_messages
  where chat_messages.event_id = p_event_id
    and chat_messages.participant_id = p_participant_id
    and chat_messages.is_admin = false
    and chat_messages.created_at > now() - interval '2 minutes';

  if recent_count >= 3 then
    retry_after_seconds := greatest(
      1,
      ceiling(extract(epoch from ((oldest_recent_at + interval '2 minutes') - now())))::integer
    );

    return jsonb_build_object(
      'ok', false,
      'code', 'MESSAGE_RATE_LIMITED',
      'message', 'Wait a little till sending again.',
      'retryAfterSeconds', retry_after_seconds
    );
  end if;

  begin
    insert into public.chat_messages (
      event_id,
      participant_id,
      user_id,
      display_name,
      body,
      status,
      client_token,
      is_admin,
      is_pinned,
      is_highlighted,
      is_liked,
      auto_publish_eligible,
      risk_flags,
      legacy_assignment_confirmed_at,
      legacy_assignment_confirmed_by
    )
    values (
      p_event_id,
      participant.id,
      null,
      participant.display_name,
      normalized_body,
      'pending',
      p_client_token,
      false,
      false,
      false,
      false,
      false,
      array[]::text[],
      null,
      null
    )
    returning * into inserted_message;
  exception
    when unique_violation then
      select *
      into existing_message
      from public.chat_messages
      where chat_messages.event_id = p_event_id
        and chat_messages.participant_id = p_participant_id
        and chat_messages.client_token = p_client_token
      limit 1;

      if existing_message.id is not null then
        return jsonb_build_object('ok', true, 'duplicate', true, 'message', public.chat_message_public_submission_payload(existing_message));
      end if;

      raise;
  end;

  begin
    classification := public.classify_chat_message(p_event_id, participant.id, inserted_message.id, normalized_body);
    v_now := clock_timestamp();

    update public.chat_messages
    set
      risk_level = classification->>'riskLevel',
      risk_score = (classification->>'riskScore')::integer,
      risk_flags = coalesce(ARRAY(SELECT jsonb_array_elements_text(classification->'riskFlags')), array[]::text[]),
      classified_at = v_now,
      classifier_version = classification->>'classifierVersion',
      auto_publish_eligible = (classification->>'autoPublishEligible')::boolean,
      status = case when classification->>'riskLevel' = 'high' then 'rejected' else 'pending' end,
      rejected_at = case when classification->>'riskLevel' = 'high' then v_now else rejected_at end,
      rejection_source = case when classification->>'riskLevel' = 'high' then 'automatic_rules' else rejection_source end,
      rejection_reason = case when classification->>'riskLevel' = 'high' then 'automatic_rules' else rejection_reason end
    where id = inserted_message.id
    returning * into inserted_message;

    insert into public.chat_message_moderation_audit (
      event_id,
      message_id,
      participant_id,
      actor_id,
      action,
      previous_status,
      new_status,
      reason,
      risk_level,
      risk_flags,
      classifier_version
    )
    values (
      inserted_message.event_id,
      inserted_message.id,
      inserted_message.participant_id,
      null,
      'message_classified',
      'pending',
      inserted_message.status,
      null,
      inserted_message.risk_level,
      inserted_message.risk_flags,
      inserted_message.classifier_version
    );

    if inserted_message.status = 'rejected' then
      insert into public.chat_message_moderation_audit (
        event_id,
        message_id,
        participant_id,
        actor_id,
        action,
        previous_status,
        new_status,
        reason,
        risk_level,
        risk_flags,
        classifier_version
      )
      values (
        inserted_message.event_id,
        inserted_message.id,
        inserted_message.participant_id,
        null,
        'message_auto_rejected',
        'pending',
        'rejected',
        'automatic_rules',
        inserted_message.risk_level,
        inserted_message.risk_flags,
        inserted_message.classifier_version
      );
    end if;
  exception
    when others then
      v_now := clock_timestamp();
      update public.chat_messages
      set
        risk_level = 'medium',
        risk_score = 0,
        risk_flags = array['CLASSIFIER_FAILURE'],
        classified_at = v_now,
        classifier_version = public.chat_message_risk_classifier_version(),
        auto_publish_eligible = false,
        status = 'pending'
      where id = inserted_message.id
      returning * into inserted_message;
  end;

  return jsonb_build_object('ok', true, 'duplicate', false, 'message', public.chat_message_public_submission_payload(inserted_message));
end;
$$;

revoke all on function public.submit_chat_message(uuid, uuid, uuid, text, uuid) from public;
grant execute on function public.submit_chat_message(uuid, uuid, uuid, text, uuid) to anon, authenticated;
drop function if exists public.submit_chat_message(uuid, uuid, text, uuid);

create or replace function public.moderate_chat_message(
  p_message_id uuid,
  p_next_status text,
  p_reason text default null
)
returns public.chat_messages
language plpgsql
security definer
set search_path = public
as $$
declare
  target_message public.chat_messages;
  updated_message public.chat_messages;
  target_event public.events;
  audit_action text;
  cleaned_reason text;
  v_now timestamptz := clock_timestamp();
begin
  if auth.uid() is null then
    raise exception 'NOT_EVENT_ADMIN';
  end if;

  if p_next_status not in ('approved', 'rejected') then
    raise exception 'INVALID_MESSAGE_STATE';
  end if;

  select chat_messages.*
  into target_message
  from public.chat_messages
  where chat_messages.id = p_message_id
  for update;

  if target_message.id is null then
    raise exception 'MESSAGE_NOT_FOUND';
  end if;

  select events.*
  into target_event
  from public.events
  where events.id = target_message.event_id
    and events.owner_id = auth.uid();

  if target_event.id is null then
    raise exception 'NOT_EVENT_ADMIN';
  end if;

  if target_message.status = p_next_status then
    return target_message;
  end if;

  if target_message.status not in ('pending', 'rejected') then
    raise exception 'MESSAGE_ALREADY_MODERATED';
  end if;

  if target_message.status = 'rejected' and p_next_status <> 'approved' then
    raise exception 'INVALID_MESSAGE_STATE';
  end if;

  cleaned_reason := nullif(left(btrim(coalesce(p_reason, '')), 240), '');
  audit_action := case when p_next_status = 'approved' then 'message_approved' else 'message_rejected' end;

  update public.chat_messages
  set
    status = p_next_status,
    approved_at = case when p_next_status = 'approved' then v_now else approved_at end,
    published_at = case when p_next_status = 'approved' then v_now else null end,
    approved_by = case when p_next_status = 'approved' then auth.uid() else approved_by end,
    approval_source = case when p_next_status = 'approved' then 'manual' else approval_source end,
    rejected_at = case when p_next_status = 'rejected' then v_now else rejected_at end,
    rejected_by = case when p_next_status = 'rejected' then auth.uid() else rejected_by end,
    rejection_reason = case when p_next_status = 'rejected' then cleaned_reason else rejection_reason end
  where id = target_message.id
  returning * into updated_message;

  insert into public.chat_message_moderation_audit (
    event_id,
    message_id,
    participant_id,
    actor_id,
    action,
    previous_status,
    new_status,
    reason,
    risk_level,
    risk_flags,
    classifier_version
  )
  values (
    target_message.event_id,
    target_message.id,
    target_message.participant_id,
    auth.uid(),
    audit_action,
    target_message.status,
    updated_message.status,
    cleaned_reason,
    target_message.risk_level,
    target_message.risk_flags,
    target_message.classifier_version
  );

  return updated_message;
end;
$$;

revoke all on function public.moderate_chat_message(uuid, text, text) from public;
grant execute on function public.moderate_chat_message(uuid, text, text) to authenticated;

notify pgrst, 'reload schema';
