import { Counter, Rate, Trend } from "k6/metrics";

export const heartbeatDuration = new Trend("heartbeat_duration", true);
export const heartbeatFailed = new Rate("heartbeat_failed");
export const submissionDuration = new Trend("submission_duration", true);
export const submissionUnexpectedFailed = new Rate("submission_unexpected_failed");
export const sessionInitDuration = new Trend("session_init_duration", true);
export const publicFetchDuration = new Trend("public_message_fetch_duration", true);
export const listenerCountDuration = new Trend("listener_count_duration", true);
export const acceptedSubmissions = new Counter("accepted_submissions");
export const intentionalRateLimits = new Counter("intentional_rate_limit_rejections");
export const unexpectedSubmissionRejections = new Counter("unexpected_submission_rejections");
export const queuedPrivateVisible = new Counter("queued_private_visible_to_sender");
export const visibilityLeak = new Counter("visibility_leak");
export const duplicatePublicDelivery = new Counter("duplicate_public_delivery");
export const pageLoadDuration = new Trend("page_load_duration", true);
export const audioProbeDuration = new Trend("audio_probe_duration", true);
export const queueWorkerDuration = new Trend("queue_worker_duration", true);
export const queueDiagnosticsDuration = new Trend("queue_diagnostics_duration", true);
export const deltaRpcCalls = new Counter("delta_rpc_calls");
export const deltaRowsReturned = new Counter("delta_rows_returned");
export const zeroRowDeltaResponses = new Counter("zero_row_delta_responses");
export const preJoinVisibilityViolation = new Counter("pre_join_visibility_violation");
export const staleScopeIncident = new Counter("stale_scope_incident");
export const reconnectRecovery = new Counter("reconnect_recovery");
export const foregroundRecovery = new Counter("foreground_recovery");
export const coalescedRecovery = new Counter("coalesced_recovery");
export const controlledPublications = new Counter("controlled_publications");
